### PR TITLE
#81 get config json from command line argument

### PR DESCRIPTION
**Pull request by SamMacy**
# Pull request questions

## Which issue does this address

Issue number: #81

### CODE REVIEW

**Review by docktermj — APPROVED** [review]

**Review by jbutcher21 — CHANGES_REQUESTED** [review]
Got some code duplication there ...  wanna try something like this?  If not resubmit (I like readable code as much as efficient, but oh that Michael!)

    # use environment variable if not specified on command line
    if os.getenv("SENZING_ENGINE_CONFIGURATION_JSON") and not args.iniFile:
        g2module_params = os.getenv("SENZING_ENGINE_CONFIGURATION_JSON")

    # Use G2Module.ini (command line option over default)
    else:

        ini_file_name = args.iniFile if args.iniFile else pathlib.Path(G2Paths.get_G2Module_ini_path())
        G2Paths.check_file_exists_and_readable(ini_file_name)
        iniParamCreator = G2IniParams()
        g2module_params = iniParamCreator.getJsonINIParams(ini_file_name)

**Comment by docktermj** [comment]
@jbutcher21,  @SamMacy and I had a discussion about the style of the code to write.  I suggested the principle of:

What is the most explicit way of showing the following precedence of input variables?

1. Command line argument
2. Environment variable
3. Configuration file in specific paths

@jbutcher21 The code you suggest is more compact, granted.  But it is not [explicit](https://docs.python-guide.org/writing/style/#explicit-code) and seems to bend away from the [Zen of Python](https://docs.python-guide.org/writing/style/#zen-of-python)'s
> Readability counts.

Perhaps there is an in-between that follows the DRY principle you advocate while keeping the code readable and explicit.

@SamMacy Feel free to ponder this and see if there is a better approach.

**Comment by docktermj** [comment]
Perhaps:

```python
    if args.iniFile:
        g2module_params = get_g2module_params_from_file(pathlib.Path(args.iniFile[0]))
    elif os.getenv("SENZING_ENGINE_CONFIGURATION_JSON"):
        g2module_params = os.getenv("SENZING_ENGINE_CONFIGURATION_JSON")
    else:
        g2module_params = get_g2module_params_from_file(pathlib.Path(G2Paths.get_G2Module_ini_path()))
```
Where a new
```
def get_g2module_params_from_file(file)
```
would need to be created.

**Review by jbutcher21 — APPROVED** [review]
All good!

**Pull request merged**
